### ISSUE TITLE
troubles with aws sam cli

### ISSUE THREAD

**Issue by cdepillabout** [theam/aws-lambda-haskell-runtime#118]
I've been trying to use aws-lambda-haskell-runtime with the AWS SAM CLI.  I've run into multiple problems.  I'll describe them in this issue.  I'm new to AWS Lambda and AWS SAM, so you should take this issue with a grain of salt.

## Resources

I learned about SAM from the [AWS SAM Developer Guide](https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/what-is-sam.html).  In particular,

- [Tutorial: Deploying a Hello World application](https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/serverless-getting-started-hello-world.html)
- [Building custom runtimes](https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/building-custom-runtimes.html)
- [Testing and Debugging](https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/serverless-test-and-debug.html)

## Setup

I've setup an example Haskell application using `aws-lambda-haskell-runtime`.  I've used `sam` to generate a `template.yaml` file, and then edited to match my Haskell application.

Here's my `sam` version:

```console
$ sam --version
SAM CLI, version 1.37.0
```

I believe I generated my `template.yaml` file with a command like `sam init`, but I forget the specifics.  You can find an example in the above resources section.

My `template.yaml` looks like the following:

```yaml
AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: |
  haskell-app

  SAM App for custom runtime with haskell

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 3

Resources:
  HeyWorldFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      Description: Says hello world
      CodeUri: .
      Handler: handler
      Runtime: provided.al2
      Events:
        HeyWorld:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /hey
            Method: post
    Metadata:
      BuildMethod: makefile

Outputs:
  # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
  # Find out more about other implicit resources you can reference within SAM
  # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
  HeyWorldApi:
    Description: "API Gateway endpoint URL for Prod stage for Hey World function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/hey/"
  HeyWorldFunction:
    Description: "Hey World Lambda Function ARN"
    Value: !GetAtt HeyWorldFunction.Arn
  HeyWorldFunctionIamRole:
    Description: "Implicit IAM Role created for Hey World function"
    Value: !GetAtt HeyWorldFunctionRole.Arn
```

The one thing to note here is that the value for `Resources.HeyWorldFunction.Properties.Handler` is `handler`.  I use this function in my Haskell application.

I have a `Makefile` for building this application that is used by `sam build`:

```Makefile
clean:
        rm -rf .aws-sam/build*

# Build application.
build:
        sam build
.PHONY: build

# Run application in Docker.
#
# XXX: hot loading doesn't work correctly if the .aws-sam/build directory exists
# for some reason.
#
# https://github.com/aws/aws-sam-cli/issues/1921
# https://github.com/aws/aws-sam-cli/issues/921
#
# Note that this works for interpreted languages (like bash) since they
# don't need a build step, but won't work for compiled languages.
#
# For compiled languages, you have to run `sam build` before `sam local
# start-api`. While `sam local start-api` is running, you have to run `sam
# build` for any changes to be reflected.
start-local:
        sam local start-api
.PHONY: start-local

invoke-local:
        sam local invoke
.PHONY: invoke-local

# This command can be used for the initial deploy.  This is just for
# documentation purposes.  I don't expect to use this.
guided-deploy: build
        sam deploy --guided
.PHONY: guided-deploy

# Re-deploy application.
#
# Note that the application has to be built
deploy: build
        sam deploy
.PHONY: deploy

# Completely delete the whole application cloudformation stack.
#
# Note that once you delete the whole application cloudformation stack,
# then you much do `make guided-deploy` to redeploy it.
destroy:
        aws cloudformation delete-stack --stack-name bash-app # --region region
.PHONY: destroy

# Validate template.yaml
validate:
        sam validate
.PHONY: validate

#############################################
## Targets used internally by `sam build`. ##
#############################################

build-HeyWorldFunction:
        cabal build
        cp ./dist-newstyle/build/x86_64-linux/ghc-9.0.2/bootstrap-0.1.0.0/x/bootstrap/build/bootstrap/bootstrap $(ARTIFACTS_DIR)/

.PHONY: build-HeyWorldFunction
```

The only important target here is `build-HeyWorldFunction` (but it is not directly related to this issue).

Here is the `.cabal` file for my application.

`bootstrap.cabal`:

```cabal
cabal-version:      2.4
name:               bootstrap
version:            0.1.0.0

executable bootstrap
    main-is:          Main.hs
    build-depends:    base == 4.15.1.0
                    , aeson
                    , amazonka-dynamodb
                    , aws-lambda-haskell-runtime
                    , bytestring
                    , base64-bytestring
                    , http-conduit
                    , text
    default-extensions:  DataKinds
                       , DefaultSignatures
                       , DeriveAnyClass
                       , DeriveFoldable
                       , DeriveFunctor
                       , DeriveGeneric
                       , DerivingStrategies
                       , EmptyCase
                       , ExistentialQuantification
                       , FlexibleContexts
                       , FlexibleInstances
                       , GADTs
                       , GeneralizedNewtypeDeriving
                       , InstanceSigs
                       , KindSignatures
                       , LambdaCase
                       , MultiParamTypeClasses
                       , NamedFieldPuns
                       , NoImplicitPrelude
                       , OverloadedLabels
                       , OverloadedLists
                       , OverloadedStrings
                       , PatternSynonyms
                       , PolyKinds
                       , RankNTypes
                       , RecordWildCards
                       , ScopedTypeVariables
                       , StandaloneDeriving
                       , TypeApplications
                       , TypeFamilies
                       , TypeOperators
    other-extensions:    TemplateHaskell
                       , QuasiQuotes
                       , UndecidableInstances
    hs-source-dirs:   app
    default-language: Haskell2010
```
