### ISSUE TITLE
Testing locally with AWS SAM

### ISSUE THREAD

**Issue by raghav-kukreti** [theam/aws-lambda-haskell-runtime#98]
OS: Debian
Stack: 2.5.1
GHC: 8.8.3

I've been trying to invoke the standard template's Handler (`src/Lib.hs`) locally to test, using 
`sam local invoke -e query.json`

where `query.json` simply contains:
```{"personName": "value1", "personAge": 22}```

Till now, I've created a `/template.yaml` file which reads:

```yaml 
AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  Lambda handlers f
Resources:
  svelteHaskell:
    Type: AWS::Serverless::Function
    Properties:
      Handler: handler
      Runtime: provided
      CodeUri: 'build/function.zip'
      Description: >
          Main Handler 
```

In place of `handler` I have tried various combinations which include:
- `'src/Lib.hs'`
- `provided`
-`Lib`

All of which gives the same error on `sam invoke`: `"Handler handler does not exist on project"`
Is there a proper way I should be testing this locally?
